#!/usr/bin/env bash

# Конфигурация
WALLPAPER_DIR="$HOME/.config/hypr/Wallpapers"
CONFIG_FILE="$HOME/.config/hypr/hyprpaper.conf"
CACHE_DIR="$HOME/.cache/wal"
MONITOR1="DP-1"
MONITOR2="DP-3"

# Проверка директории
if [ ! -d "$WALLPAPER_DIR" ]; then
    echo "Ошибка: Директория $WALLPAPER_DIR не существует!"
    exit 1
fi

# Получаем список файлов
files=()
while IFS= read -r -d $'\0' file; do
    files+=("$file")
done < <(find "$WALLPAPER_DIR" -maxdepth 1 -type f \( \
    -iname "*.jpg" -o \
    -iname "*.jpeg" -o \
    -iname "*.png" -o \
    -iname "*.webp" \) -print0 2>/dev/null | sort -z)

# Проверка наличия файлов
if [ ${#files[@]} -eq 0 ]; then
    echo "Ошибка: В директории $WALLPAPER_DIR нет изображений!"
    exit 1
fi

# Функция выбора обоев
select_wallpaper() {
    local monitor=$1
    local default_num=$2
    
    echo ""
    echo "Выберите обои для $monitor:"

    while true; do
        read -p "Введите номер обоев (1-${#files[@]}) [по умолчанию $default_num]: " num
        
        # Если нажат Enter, используем значение по умолчанию
        if [[ -z "$num" ]]; then
            num=$default_num
        fi
        
        if [[ ! "$num" =~ ^[0-9]+$ ]]; then
            echo "Ошибка: Введите число!"
            continue
        fi
        
        if (( num < 1 || num > ${#files[@]} )); then
            echo "Ошибка: Номер должен быть от 1 до ${#files[@]}!"
            continue
        fi
        
        selected="${files[num-1]}"
        echo "wallpaper = $monitor,$selected" >> "$CONFIG_FILE"
        
        # Для первого монитора применяем pywal
        if [ "$monitor" == "$MONITOR1" ]; then
            echo "Применяем pywal для $selected"
            wal -q -i "$selected"
            
            # Применяем цвета для Kitty
            if [ -f "$CACHE_DIR/colors-kitty.conf" ]; then
                echo "Обновляем цвета Kitty..."
                kitten @ set-colors --all --configured "$CACHE_DIR/colors-kitty.conf"
            fi
            
            # Обновляем Waybar (если используется)
            if pgrep waybar >/dev/null; then
                echo "Перезагружаем Waybar..."
                pkill -USR2 waybar
            fi
        fi
        
        break
    done
}

# Очищаем конфиг и добавляем preload
echo "# Generated by hyprpaper script" > "$CONFIG_FILE"
for img in "${files[@]}"; do
    echo "preload = $img" >> "$CONFIG_FILE"
done

# Выводим список с номерами
echo "Доступные обои:"
for i in "${!files[@]}"; do
    printf "%3d) %s\n" $((i+1)) "$(basename "${files[i]}")"
done

# Выбор для каждого монитора
select_wallpaper "$MONITOR1" 1  # По умолчанию первая картинка для первого монитора
select_wallpaper "$MONITOR2" 2  # По умолчанию вторая картинка для второго монитора

# Перезапускаем hyprpaper
echo "Перезапускаем hyprpaper..."
killall hyprpaper 2>/dev/null
hyprpaper & disown

echo "Обои успешно изменены!"
